### ISSUE TITLE
Feature request: define DOM path(s) to check

### ISSUE THREAD

**Issue by joohoi** [AnttiKurittu/flinch#1]
In pages with highly dynamic content it would be very beneficial to be able to define / exclude DOM paths to use for difference calculation

**Comment by AnttiKurittu** [comment]
The script currently discards all tags and calculates the content difference from the text output only. What I'm trying to do with this is to track a bunch of phishing pages to see which ones are still active, and for that just reading the text content is enough to see if the page is down and something else, like hosting service notice, is up.

It could be implemented with an argument (like --exclude) and passing that onto bs4 before processing the page. I'll have to look into how to correctly do it without making things too complicated.

**Comment by joohoi** [comment]
Yeah, this feature request unlikely fits that scenario, however it would extend the usability for pretty much every other kind of page monitoring.

**Comment by AnttiKurittu** [comment]
That is true, I'd imagine you'd want something that runs periodically with cron or something and sends you an (email?) alert for changes. I'll see if I get into the mood of updating this, we'll run it for a while and get some experiences. If you feel like implementing something like that, feel free to throw me the end result ;)
